### PR TITLE
Fix cursor position when weapon FOV does not match player FOV

### LINKED ISSUE #35: ImGUI on viewmodel doesn't properly find cursor position
**
image
**

the white crosss is imgui.CursorPos as reported by imgui, the mouse is the actual cursor pos
the imgui panel is attached to the player's viewmodel
at screen middle they're the same

i'm thinking this might be an issue with EyePos being too close to the viewmodel?

### PR DESCRIPTION
**Pull request by dhkatz**
This is a PR which fixes #35 

As far as I can tell this hasn't broken anything else but if someone can confirm that would be great.

I ended up adding a new function specifically for weapons because we only want to do FOV corrects for view models. 

I did not automatically convert the position and angles using `ENTITY:LocalToWorld(pos)` because I assumed most people will be positioning view model UI relative to bone positions and `ENTITY:GetBonePosition(n)` always returns values in world space coordinates.

Before Fix:

https://github.com/wyozi-gmod/imgui/assets/8341611/be1b8c26-5bd8-4c32-b11b-a447c3dc861c

Notice how the mouse does not line up with the cursor while the screen clicker is active (the virtual cursor is being rendered by the weapon's `SWEP:PostDrawViewMode`)

After Fix:

https://github.com/wyozi-gmod/imgui/assets/8341611/d42aafc4-5370-4436-9cb1-8776b70dddbb

I can interact with both the button positioned in the world **and** the button positioned on the view model accurately to the mouse cursor.

### CODE REVIEW

File: imgui.lua [hunk 1]
```diff
@@ -35,7 +35,7 @@ local function shouldAcceptInput()
 	end
 
 	-- don't process input if we're doing VGUI stuff (and not in context menu)
-	if vgui.CursorVisible() and vgui.GetHoveredPanel() ~= g_ContextMenu then
+	if vgui.CursorVisible() and vgui.GetHoveredPanel() ~= g_ContextMenu and not vgui.IsHoveringWorld() then
```
Comment (dhkatz) [inline imgui.lua:38]: This change seemed necessary because when calling `gui.EnableScreenClicker(true)` in my weapon to bring up the mouse, input did not seem to be accepted because I was hovering the world panel.

**Comment by dhkatz** [comment]
Ok it looks like this did break some things, so I might need to add a specific function for weapons like entities have

**Comment by dhkatz** [comment]
Ok I seem to have fixed the issues by adding a new function to only correct FOV using view model when rendering for a weapon

**Review by wyozi — APPROVED** [review]
Looks good, thanks. If you can just add ScrW and ScrH to .luacheckrc, I can merge this. Could also add a short mention to README

**Comment by wyozi** [comment]
Good stuff
